openapi: 3.0.1
info:
  title: Product Summary
  description: "# Product Summary\n# Product Summary API Documentation\n\n    A product\
    \ is a financial instrument such as a credit or debit card, a business current\
    \ account, or a 25 year fixed rate mortgage.\n    An arrangement is an instance\
    \ of a product. For example, Mrs Jones' fixed rate mortgage. \n    An arrangement\
    \ represents a financial agreement between one party and another party, typically\
    \ between the customer and the bank.\n    Typically, an arrangement will be a\
    \ financial product that the customer has with the bank - accounts, loans, mortgages\
    \ and credit cards are all examples of arrangements.\n    However, other agreements\
    \ are also modeled as arrangements, e.g. direct debits and standard orders.\n\
    \    Currently the product summary API will contain the following operations.\n\
    \    \n    * List all products\n    * List all arrangements\n    * List arrangements\
    \ depending on privilege, business function and resource name\n"
  version: v2
servers:
  - url: /arrangement-manager/
    description: The server
tags:
  - name: product summary
paths:
  /client-api/v2/productsummary:
    summary: ProductSummary
    description: Retrieve all product summaries.
    get:
      tags:
        - productsummary
      summary: Retrieve list of products summaries.
      description: Retrieve list of products summaries.
      operationId: getProductSummary
      parameters:
        - name: Content-Language
          in: header
          description: Defines the translation natural language as specified in ISO
            639-1, and territory two-letter form of ISO 3166.
          required: false
          schema:
            type: string
          examples:
            example:
              summary: example
        - name: debitAccount
          in: query
          description: Type of account
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: creditAccount
          in: query
          description: Type of account
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: maskIndicator
          in: query
          description: Masked/Unmasked card number
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: false
      responses:
        "200":
          description: |
            #### Product list

                Initial call to retrieve the list of products.
                Count of items is in `X-Total-Count` header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSummaryGet'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              example:
                $ref: '#/components/examples/BadRequestError'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              example:
                $ref: '#/components/examples/InternalServerError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              example:
                $ref: '#/components/examples/ForbiddenError'
      x-BbAccessControl-resource: Product Summary
      x-BbAccessControl-function: Product Summary
      x-BbAccessControl-privilege: view
  /client-api/v2/productsummary/configuration:
    summary: ProductSummaryEntitlementsByLegalEntityId
    description: Retrieve product summaries for arrangements needed for entitlements
      configuration.
    get:
      tags:
        - productsummary
      summary: Retrieve list of products summaries, flat structure.
      description: Retrieve list of products summaries, flat structure.
      operationId: getProductSummaryEntitlementsByLegalEntityId
      parameters:
        - name: legalEntityIds
          in: query
          description: No description available
          required: true
          schema:
            type: array
            items:
              type: string
          examples:
            example:
              summary: example
              value:
                - 0e4c1c09-fcf4-42fe-ae57-342603d8ef82
                - 53f023cd-c016-4d19-bdf1-8d83f98c11e1
                - c0a20cc4-5e15-42d4-94a6-1101ed6c1c37
        - name: arrangementIds
          in: query
          description: No description available
          required: false
          schema:
            type: array
            items:
              type: string
          examples:
            example:
              summary: example
              value:
                - 6bd1bed8-75b6-4c53-b1d4-0751af5494f2
                - a0eb0dab-cd05-4423-bdb9-81e838fc9046
        - name: ignoredArrangementIds
          in: query
          description: No description available
          required: false
          schema:
            type: array
            items:
              type: string
          examples:
            example:
              summary: example
              value:
                - 2ab5b5c8-a4bc-4f25-bfb6-4aed7dc9882e
        - name: searchTerm
          in: query
          description: Full text search
          required: false
          schema:
            maxLength: 256
            type: string
          examples:
            example:
              summary: example
              value: Account X
        - name: from
          in: query
          description: Page Number. Skip over pages of elements by specifying a start
            value for the query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
          examples:
            example:
              summary: example
              value: 20
        - name: cursor
          in: query
          description: |
            Record UUID. As an alternative for specifying 'from' this allows to point to the record to start the selection from.
          required: false
          schema:
            type: string
            default: ""
          examples:
            example:
              summary: example
              value: 76d5be8b-e80d-4842-8ce6-ea67519e8f74
        - name: size
          in: query
          description: |
            Limit the number of elements on the response. When used in combination with cursor, the value
            is allowed to be a negative number to indicate requesting records upwards from the starting point indicated
            by the cursor.
          required: false
          schema:
            type: integer
            format: int32
            default: 10
          examples:
            example:
              summary: example
              value: 80
        - name: orderBy
          in: query
          description: |
            Order by field: "name","bankAlias","bookedBalance","availableBalance","creditLimit","IBAN","BBAN","BIC","currency","externalTransferAllowed","urgentTransferAllowed","accruedInterest","principalAmount","currentInvestmentValue","productNumber","accountOpeningDate","accountInterestRate","valueDateBalance","creditLimitUsage","creditLimitInterestRate","creditLimitExpiryDate","startDate","termUnit","termNumber","maturityDate","maturityAmount","autoRenewalIndicator","interestPaymentFrequencyUnit","interestPaymentFrequencyNumber","interestSettlementAccount","outstandingPrincipalAmount","monthlyInstalmentAmount","amountInArrear","minimumRequiredBalance","creditCardAccountNumber","validThru","applicableInterestRate","remainingCredit","outstandingPayment","minimumPayment","minimumPaymentDueDate","totalInvestmentValue","accountHolderAddressLine1","accountHolderAddressLine2","accountHolderStreetName","postCode","town","countrySubDivision","accountHolderCountry","creditAccount","debitAccount","productKindName","productTypeName"
          required: false
          schema:
            type: string
          examples:
            example:
              summary: example
        - name: direction
          in: query
          description: Direction
          required: false
          schema:
            type: string
            default: DESC
            enum:
              - ASC
              - DESC
          examples:
            example:
              summary: example
      responses:
        "200":
          description: "#### Product summary by legal entity id\n\n    Initial call\
            \ to retrieve the paginated list of product summary by legal entity id.\n\
            \    \n    Count of items is in `X-Total-Count` header.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSummaryFlatStructureGet'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              example:
                $ref: '#/components/examples/BadRequestError'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              example:
                $ref: '#/components/examples/InternalServerError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              example:
                $ref: '#/components/examples/ForbiddenError'
      x-BbAccessControl-resource: Entitlements
      x-BbAccessControl-function: Manage Data Groups
      x-BbAccessControl-privilege: view
  /client-api/v2/productsummary/context/arrangements:
    summary: Arrangements by business function
    description: Endpoint for accessing arrangements for the current context.
    get:
      tags:
        - productsummary
      summary: Get a list of arrangements according to a given business functions.
      description: Get a list of arrangements according to a given business functions
      operationId: getArrangementsByBusinessFunction
      parameters:
        - name: Content-Language
          in: header
          description: Defines the translation natural language as specified in ISO
            639-1, and territory two-letter form of ISO 3166.
          required: false
          schema:
            type: string
          examples:
            example:
              summary: example
        - name: withLatestBalances
          in: query
          description: Retrieve a list of arrangements with the latest balances
          required: false
          schema:
            type: boolean
            default: true
          examples:
            example:
              summary: example
              value: true
        - name: maskIndicator
          in: query
          description: Masked/Unmasked card number
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: false
        - name: debitAccount
          in: query
          description: Type of account
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: creditAccount
          in: query
          description: Type of account
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: businessFunction
          in: query
          description: Provide comma separated contexts for retrieving arrangements
          required: true
          schema:
            type: string
          examples:
            example:
              summary: example
              value: Product Summary
        - name: resourceName
          in: query
          description: Provide the resource for retrieving arrangements
          required: true
          schema:
            type: string
          examples:
            example:
              summary: example
              value: Product Summary
        - name: privilege
          in: query
          description: Privilege for the arrangements
          required: true
          schema:
            type: string
          examples:
            example:
              summary: example
              value: view
        - name: externalTransferAllowed
          in: query
          description: Privilege for external transfers
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: false
        - name: productKindName
          in: query
          description: Product Kind Name
          required: false
          schema:
            type: string
          examples:
            example:
              summary: example
              value: Current Account
        - name: legalEntityIds
          in: query
          description: A list of legal entities ids to filter by
          required: false
          schema:
            type: array
            items:
              type: string
          examples:
            example:
              summary: example
              value:
                - 0e4c1c09-fcf4-42fe-ae57-342603d8ef82
                - 53f023cd-c016-4d19-bdf1-8d83f98c11e1
                - c0a20cc4-5e15-42d4-94a6-1101ed6c1c37
        - name: sourceId
          in: query
          description: No description available
          required: false
          schema:
            maxLength: 11
            type: string
          examples:
            example:
              summary: example
              value: LJBASI2XXXX
        - name: favorite
          in: query
          description: Indicates whether an arrangement is favorite for a user or not
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: searchTerm
          in: query
          description: Full text search
          required: false
          schema:
            maxLength: 256
            type: string
          examples:
            example:
              summary: example
              value: Account X
        - name: customOrder
          in: query
          description: Parameter that identifies weather the returned list should be
            ordered by custom order/grouping
          required: false
          schema:
            type: boolean
          examples:
            example:
              summary: example
              value: true
        - name: favoriteFirst
          in: query
          description: Parameter that sets favorite arrangements on top when true
          required: false
          schema:
            type: boolean
            default: false
          examples:
            example:
              summary: example
              value: true
        - name: from
          in: query
          description: Page Number. Skip over pages of elements by specifying a start
            value for the query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
          examples:
            example:
              summary: example
              value: 20
        - name: cursor
          in: query
          description: |
            Record UUID. As an alternative for specifying 'from' this allows to point to the record to start the selection from.
          required: false
          schema:
            type: string
            default: ""
          examples:
            example:
              summary: example
              value: 76d5be8b-e80d-4842-8ce6-ea67519e8f74
        - name: size
          in: query
          description: |
            Limit the number of elements on the response. When used in combination with cursor, the value
            is allowed to be a negative number to indicate requesting records upwards from the starting point indicated
            by the cursor.
          required: false
          schema:
            type: integer
            format: int32
            default: 10
          examples:
            example:
              summary: example
              value: 80
        - name: orderBy
          in: query
          description: |
            Order by field: "name","bankAlias","bookedBalance","availableBalance","creditLimit","IBAN","BBAN","BIC","currency","externalTransferAllowed","urgentTransferAllowed","accruedInterest","principalAmount","currentInvestmentValue","productNumber","accountOpeningDate","accountInterestRate","valueDateBalance","creditLimitUsage","creditLimitInterestRate","creditLimitExpiryDate","startDate","termUnit","termNumber","maturityDate","maturityAmount","autoRenewalIndicator","interestPaymentFrequencyUnit","interestPaymentFrequencyNumber","interestSettlementAccount","outstandingPrincipalAmount","monthlyInstalmentAmount","amountInArrear","minimumRequiredBalance","creditCardAccountNumber","validThru","applicableInterestRate","remainingCredit","outstandingPayment","minimumPayment","minimumPaymentDueDate","totalInvestmentValue","accountHolderAddressLine1","accountHolderAddressLine2","accountHolderStreetName","postCode","town","countrySubDivision","accountHolderCountry","creditAccount","debitAccount","productKindName","productTypeName","sourceId"
          required: false
          schema:
            type: string
          examples:
            example:
              summary: example
        - name: direction
          in: query
          description: Direction
          required: false
          schema:
            type: string
            default: DESC
            enum:
              - ASC
              - DESC
          examples:
            example:
              summary: example
      responses:
        "200":
          description: "#### Product summary by legal entity id\n\n    Initial call\
            \ to retrieve the paginated list of product summary by legal entity id.\n\
            \    \n    Count of items is in `X-Total-Count` header.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSummaryFlatStructureGet'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              example:
                $ref: '#/components/examples/BadRequestError'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              example:
                $ref: '#/components/examples/InternalServerError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              example:
                $ref: '#/components/examples/ForbiddenError'
      x-BbAccessControl-resource: Product Summary
      x-BbAccessControl-function: Product Summary
      x-BbAccessControl-privilege: view
components:
  schemas:
    DebitCardsItem:
      $ref: schemas/summary/types/debit-card-item.yaml
    ProductSummaryFlatStructureGet:
      $ref: schemas/summary/productsummary-flat-structure-get.yaml
    ProductSummaryItem:
      $ref: schemas/summary/productsummary-item.yaml
    PresentationProductItem:
      $ref: schemas/summary/product-item.yaml
    PresentationProductKindItem:
      $ref: schemas/summary/product-kind-item.yaml
    PresentationUserPreferences:
      $ref: schemas/summary/user-preferences.yaml
    StateItemQ:
      $ref: schemas/summary/state-item.yaml
    Unit:
      $ref: schemas/summary/types/time-unit.yaml
    ProductSummaryGet:
      $ref: schemas/summary/productsummary-get.yaml
    AggregatedBalance:
      $ref: schemas/summary/aggregated-balance.yaml
    BaseProductSummary:
      $ref: schemas/summary/products/base-product.yaml
    CurrentAccount:
      $ref: schemas/summary/products/current-account.yaml
    SavingsAccount:
      $ref: schemas/summary/products/savings-account.yaml
    TermDeposit:
      $ref: schemas/summary/products/term-deposit.yaml
    Loan:
      $ref: schemas/summary/products/loan.yaml
    CreditCard:
      $ref: schemas/summary/products/credit-card.yaml
    DebitCard:
      $ref: schemas/summary/products/debit-card.yaml
    InvestmentAccount:
      $ref: schemas/summary/products/investment-account.yaml
    CustomProductKind:
      $ref: schemas/summary/products/custom-product-kind.yaml
    GeneralAccount:
      $ref: schemas/summary/products/general-account.yaml

    AccountHolderName:
      maxLength: 256
      type: string
      description: This field is deprecated from 2.17.1 version. It will be removed
        in 2.19.0 and will be replaced with 'accountHolderNames'.
      deprecated: true
    AccountHolderNames:
      maxLength: 256
      type: string
      description: Party(s) with a relationship to the account.
    AccountHolderAddressLine1:
      maxLength: 70
      type: string
      description: Address of the Payer/Payee - Alternate address line for the account.
    AccountHolderAddressLine2:
      maxLength: 70
      type: string
      description: Address of the Payer/Payee - Alternate address line for the account.
    AccountHolderCountry:
      pattern: ^[A-Z]{2}$
      type: string
      description: Country of the account holder
    AccountHolderStreetName:
      maxLength: 70
      type: string
      description: Street name of the Payer/Payee - Alternate street name for the
        account.
    AccountInterestRate:
      type: number
      description: The annualized cost of credit or debt-capital computed as the percentage
        ratio of interest to the principal.
    AccountOpeningDate:
      type: string
      format: date-time
    AccruedInterest:
      type: number
    AmountInArrear:
      type: number
      description: The part of a debt that is overdue after missing one or more required
        payments. The amount of the arrears is the amount accrued from the date on
        which the first missed payment was due.
    ApplicableInterestRate:
      type: number
      description: The interest rate or rates which would be used for a particular
        arrangement.
    AutoRenewalIndicator:
      type: boolean
      description: Indicates whether or not an arrangement is to be continued after
        maturity automatically. Usually the product is renewed using the same principal
        and term unless renegotiation has taken place prior to expiration.
    BankAlias:
      maxLength: 50
      type: string
      description: The name that can be assigned by the bank to label the arrangement.
    BankBranchCode:
      maxLength: 20
      type: string
      description: (This is to accomodate additional country specific fields like
        Sort Code in UK)
    BBAN:
      maxLength: 50
      type: string
      description: Specifying the BBAN of the account.
    BIC:
      maxLength: 11
      type: string
      description: Bank Identifier Code - international bank code that identifies
        particular banks worldwide
    CardNumber:
      type: number
    CountrySubDivision:
      maxLength: 35
      type: string
    CreditAccount:
      type: boolean
      description: Indicator whether or not the arrangement can be used in payment
        orders as credit account.
    CreditCardAccountNumber:
      maxLength: 32
      type: string
      description: The number of the account the credit card transactions settle on
        (so actually the reference to the settlement account of the card)?
    CreditLimitExpiryDate:
      type: string
      description: The date after which overdraft will no longer be available to the
        account (renewed automatically or cancelled).
      format: date-time
    CreditLimitInterestRate:
      type: number
      description: Overdraft Interest is an interest applied to the account for any
        time throughout the month when the account is overdrawn.
    CreditLimitUsage:
      type: number
      description: Monetary amount of the used overdraft.
    CrossCurrency:
      type: boolean
      description: Defines if cross currency transfer is allowed
    CurrencyCode:
      type: string
    CurrencyValue:
      type: string
    DebitAccount:
      type: boolean
      description: Indicator whether or not the arrangement can be used in payment
        orders as debit account.
    ExternalTransfer:
      type: boolean
      description: Defines if transfer to another party is allowed.
    IBAN:
      maxLength: 34
      pattern: ^(AF|AX|AL|DZ|AS|AD|AO|AI|AQ|AG|AR|AM|AW|AU|AT|AZ|BS|BH|BD|BB|BY|BE|BZ|BJ|BM|BT|BO|BQ|BA|BW|BV|BR|IO|BN|BG|BF|BI|KH|CM|CA|CV|KY|CF|TD|CL|CN|CX|CC|CO|KM|CG|CD|CK|CR|CI|HR|CU|CW|CY|CZ|DK|DJ|DM|DO|EC|EG|SV|GQ|ER|EE|ET|FK|FO|FJ|FI|FR|GF|PF|TF|GA|GM|GE|DE|GH|GI|GR|GL|GD|GP|GU|GT|GG|GN|GW|GY|HT|HM|VA|HN|HK|HU|IS|IN|ID|IR|IQ|IE|IM|IL|IT|JM|JP|JE|JO|KZ|KE|KI|KP|KR|KW|KG|LA|LV|LB|LS|LR|LY|LI|LT|LU|MO|MK|MG|MW|MY|MV|ML|MT|MH|MQ|MR|MU|YT|MX|FM|MD|MC|MN|ME|MS|MA|MZ|MM|NA|NR|NP|NL|NC|NZ|NI|NE|NG|NU|NF|MP|NO|OM|PK|PW|PS|PA|PG|PY|PE|PH|PN|PL|PT|PR|QA|RE|RO|RU|RW|BL|SH|KN|LC|MF|PM|VC|WS|SM|ST|SA|SN|RS|SC|SL|SG|SX|SK|SI|SB|SO|ZA|GS|SS|ES|LK|SD|SR|SJ|SZ|SE|CH|SY|TW|TJ|TZ|TH|TL|TG|TK|TO|TT|TN|TR|TM|TC|TV|UG|UA|AE|GB|US|UM|UY|UZ|VU|VE|VN|VG|VI|WF|EH|YE|ZM|ZW).*
      type: string
      description: Specifying the IBAN of the account.
    InterestPaymentFrequencyNumber:
      type: number
    InterestPaymentFrequencyUnit:
      $ref: '#/components/schemas/Unit'
      description: Number of times per year when the accumulated interest is settled to the account on a regular basis. The frequency could be yearly, half-yearly, quarterly, monthly, weekly, daily (or not at all, until maturity).
    InterestSettlementAccount:
      maxLength: 32
      type: string
      description: Account that provides quick access to accumulated cash to facilitate
        daily settlements with other businesses.
    LastUpdateDate:
      type: string
      description: Last date of parameter update for the arrangement.
      format: date-time
    MaturityAmount:
      type: number
      description: Amount payable at the end of a holding period of a product (maturity
        date). For deposit all of the interest is usualy paid at maturity date (IF
        the term is shorter then one year).
    MaturityDate:
      type: string
      description: End term of a holding period.
      format: date-time
    MinimumRequiredBalance:
      type: number
      description: Minimum amount that a customer must have in an account in order
        to receive some sort of service, such as keeping the account open or receive
        interest.
    MinimumPayment:
      type: number
      description: The minimum payment set a percentage of balance, or a fixed cash
        amount.
    MinimumPaymentDueDate:
      type: string
      description: Minimum Payment Due Date shown on your monthly statement to remain
        in good standing.
      format: date-time
    MonthlyInstalmentAmount:
      type: number
      description: A fixed payment amount paid by a borrower to the bank at a specified
        date each calendar month.
    Number:
      maxLength: 36
      type: string
      description: First 6 and/or last 4 digits of a Payment card. All other digits
        will/to be masked. Be aware that using card number differently is potential
        PCI risk.
    OutstandingPayment:
      type: number
    OutstandingPrincipalAmount:
      type: number
      description: This IS the value date balance of the arrangement.
    ParentId:
      maxLength: 36
      type: string
      description: Reference to the parent of the arrangement.
    PostCode:
      maxLength: 16
      type: string
    PrincipalAmount:
      type: number
    ProductId:
      maxLength: 36
      type: string
      description: Reference to the product of which the arrangement is an instantiation.
    ProductKindName:
      maxLength: 50
      minLength: 1
      type: string
      description: The label/name that is used for the respective product kind
    ProductName:
      type: string
    ProductNumber:
      maxLength: 36
      type: string
      description: The number identifying the contract.
    ProductTypeName:
      maxLength: 50
      type: string
      description: The label/name that is used to label a specific product type
    ProductVisible:
      type: boolean
      description: indicator whether to show or hide the arrangement on the widget
    RemainingCredit:
      type: number
    SourceId:
      maxLength: 11
      type: string
      description: Indicate if the account is regular or external
    StartDate:
      type: string
      format: date-time
    TermUnit:
      $ref: '#/components/schemas/Unit'
      description: The period of time and/or the interest rate arranged between Bank and customer.
    TermNumber:
      type: number
      description: The number of times interest rate is paid on the settlement account.
    Town:
      maxLength: 35
      type: string
      description: Town of the Payer/Payee - Alternate town for the account.
    UrgentTransfer:
      type: boolean
      description: Defines if urgent transfer is allowed.
    ValueDateBalance:
      type: number
      description: The balance of the account on a specific date that needs to be
        used for the calculation of interest. NB! If no date is specified (like for
        the book date balance) the current date can be assumed.
    ValidThru:
      type: string
      description: Expiration date of a credit card, after which is no longer valid.
      format: date-time
    BbAccessControl:
      required:
        - function
        - privilege
        - resource
      type: object
      properties:
        resource:
          type: string
          description: Resource being protected, e.g. 'User'
        function:
          type: string
          description: Business function, e.g. 'Manage Users'
        privilege:
          type: string
          description: The privilege required, e.g. 'view'
    BbApiDeprecation:
      required:
        - deprecatedFromVersion
        - description
        - reason
        - removedFromVersion
      type: object
      properties:
        deprecatedFromVersion:
          type: string
          description: Version of the product from which the endpoint has been deprecated
            and should no longer be used
          deprecated: true
        removedFromVersion:
          type: string
          description: Version of the product from which the API endpoint will be
            removed
        reason:
          type: string
          description: The reason the API endpoint was deprecated
          deprecated: true
        description:
          type: string
          description: Any further information, e.g. migration information
    ErrorItem:
      $ref: lib/schemas/error-item.yaml
    UnauthorizedError:
      $ref: lib/schemas/unauthorized-error.yaml
    BadRequestError:
      $ref: lib/schemas/bad-request-error.yaml
    NotFoundError:
      $ref: lib/schemas/not-found-error.yaml
    ForbiddenError:
      $ref: lib/schemas/forbidden-error.yaml
    InternalServerError:
      $ref: lib/schemas/internal-server-error.yaml
    NotAcceptableError:
      $ref: lib/schemas/not-acceptable-error.yaml
  examples:
    ProductSummaryFlatStructureGet:
      value:
        $ref: examples/summary/productsummary-flat-structure-get.json
    ProductSummaryGet:
      value:
        $ref: examples/summary/productsummary-get.json
    UnauthorizedError:
      value:
        $ref: lib/examples/unauthorized-error.json
    BadRequestError:
      value:
        $ref: lib/examples/bad-request-validation-error.json
    ForbiddenError:
      value:
        $ref: lib/examples/forbidden-error.json
    NotFoundError:
      value:
        $ref: lib/examples/not-found-error.json
    InternalServerError:
      value:
        $ref: lib/examples/internal-server-error.json
    NotAcceptableError:
      value:
        $ref: lib/examples/not-acceptable-error.json