openapi: 3.0.1
info:
  title: Product Summary
  description: "# Product Summary\n# Product Summary API Documentation\n\n    A product\
    \ is a financial instrument such as a credit or debit card, a business current\
    \ account, or a 25 year fixed rate mortgage.\n    An arrangement is an instance\
    \ of a product. For example, Mrs Jones' fixed rate mortgage. \n    An arrangement\
    \ represents a financial agreement between one party and another party, typically\
    \ between the customer and the bank.\n    Typically, an arrangement will be a\
    \ financial product that the customer has with the bank - accounts, loans, mortgages\
    \ and credit cards are all examples of arrangements.\n    However, other agreements\
    \ are also modeled as arrangements, e.g. direct debits and standard orders.\n\
    \    Currently the product summary API will contain the following operations.\n\
    \    \n    * List all products\n    * List all arrangements\n    * List arrangements\
    \ depending on privilege, business function and resource name\n"
  version: v2
servers:
- url: /arrangement-manager/
  description: The server
tags:
- name: product summary
paths:
  /service-api/v2/productsummary/context/arrangements:
    summary: Arrangements by business function
    description: Endpoint for accessing arrangements for the current context.
    get:
      tags:
      - productsummary
      summary: Get a list of arrangements according to a given business function.
      description: Get a list of arrangements according to a given business function
      operationId: getArrangementsByBusinessFunction
      parameters:
      - name: withLatestBalances
        in: query
        description: Retrieve a list of arrangements with the latest balances
        required: false
        schema:
          type: boolean
          default: true
        examples:
          example:
            summary: example
            value: true
      - name: maskIndicator
        in: query
        description: Masked/Unmasked card number
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: false
      - name: debitAccount
        in: query
        description: Type of account
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: true
      - name: creditAccount
        in: query
        description: Type of account
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: true
      - name: businessFunction
        in: query
        description: Provide comma separated contexts for retrieving arrangements
        required: true
        schema:
          type: string
        examples:
          example:
            summary: example
            value: Product Summary
      - name: resourceName
        in: query
        description: Provide the resource for retrieving arrangements
        required: true
        schema:
          type: string
        examples:
          example:
            summary: example
            value: Product Summary
      - name: privilege
        in: query
        description: Privilege for the arrangements
        required: true
        schema:
          type: string
        examples:
          example:
            summary: example
            value: view
      - name: externalTransferAllowed
        in: query
        description: Privilege for external transfers
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: false
      - name: productKindName
        in: query
        description: Product Kind Name
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
            value: Current Account
      - name: legalEntityIds
        in: query
        description: A list of legal entities ids to filter by
        required: false
        schema:
          type: array
          items:
            type: string
        examples:
          example:
            summary: example
            value:
            - 0e4c1c09-fcf4-42fe-ae57-342603d8ef82
            - 53f023cd-c016-4d19-bdf1-8d83f98c11e1
            - c0a20cc4-5e15-42d4-94a6-1101ed6c1c37
      - name: sourceId
        in: query
        description: No description available
        required: false
        schema:
          maxLength: 11
          type: string
        examples:
          example:
            summary: example
            value: LJBASI2XXXX
      - name: favorite
        in: query
        description: Indicates whether an arrangement is favorite for a user or not
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: true
      - name: searchTerm
        in: query
        description: Full text search
        required: false
        schema:
          maxLength: 256
          type: string
        examples:
          example:
            summary: example
            value: Account X
      - name: customOrder
        in: query
        description: Parameter that identifies weather the returned list should be
          ordered by custom order/grouping
        required: false
        schema:
          type: boolean
        examples:
          example:
            summary: example
            value: true
      - name: favoriteFirst
        in: query
        description: Parameter that sets favorite arrangements on top when true
        required: false
        schema:
          type: boolean
          default: false
        examples:
          example:
            summary: example
            value: true
      - name: from
        in: query
        description: Page Number. Skip over pages of elements by specifying a start
          value for the query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
        examples:
          example:
            summary: example
            value: 20
      - name: cursor
        in: query
        description: |
          Record UUID. As an alternative for specifying 'from' this allows to point to the record to start the selection from.
        required: false
        schema:
          type: string
          default: ""
        examples:
          example:
            summary: example
            value: 76d5be8b-e80d-4842-8ce6-ea67519e8f74
      - name: size
        in: query
        description: |
          Limit the number of elements on the response. When used in combination with cursor, the value
          is allowed to be a negative number to indicate requesting records upwards from the starting point indicated
          by the cursor.
        required: false
        schema:
          type: integer
          format: int32
          default: 10
        examples:
          example:
            summary: example
            value: 80
      - name: orderBy
        in: query
        description: |
          Order by field: "name","bankAlias","bookedBalance","availableBalance","creditLimit","IBAN","BBAN","BIC","currency","externalTransferAllowed","urgentTransferAllowed","accruedInterest","principalAmount","currentInvestmentValue","productNumber","accountOpeningDate","accountInterestRate","valueDateBalance","creditLimitUsage","creditLimitInterestRate","creditLimitExpiryDate","startDate","termUnit","termNumber","maturityDate","maturityAmount","autoRenewalIndicator","interestPaymentFrequencyUnit","interestPaymentFrequencyNumber","interestSettlementAccount","outstandingPrincipalAmount","monthlyInstalmentAmount","amountInArrear","minimumRequiredBalance","creditCardAccountNumber","validThru","applicableInterestRate","remainingCredit","outstandingPayment","minimumPayment","minimumPaymentDueDate","totalInvestmentValue","accountHolderAddressLine1","accountHolderAddressLine2","accountHolderStreetName","postCode","town","countrySubDivision","accountHolderCountry","creditAccount","debitAccount","productKindName","productTypeName"
        required: false
        schema:
          type: string
        examples:
          example:
            summary: example
      - name: direction
        in: query
        description: Direction
        required: false
        schema:
          type: string
          default: DESC
          enum:
          - ASC
          - DESC
        examples:
          example:
            summary: example
      responses:
        "200":
          description: "#### Product summary by legal entity id\n\n    Initial call\
            \ to retrieve the paginated list of product summary by legal entity id.\n\
            \    \n    Count of items is in `X-Total-Count` header.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSummaryFlatStructureGet'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
              example:
                $ref: '#/components/examples/BadRequestError'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
              example:
                $ref: '#/components/examples/InternalServerError'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
              example:
                $ref: '#/components/examples/ForbiddenError'
      x-BbAccessControl-resource: Product Summary
      x-BbAccessControl-function: Product Summary
      x-BbAccessControl-privilege: view
components:
  schemas:
    AccountHolderName:
      maxLength: 256
      type: string
      description: This field is deprecated from 2.17.1 version. It will be removed
        in 2.19.0 and will be replaced with 'accountHolderNames'.
      deprecated: true
    AccountHolderNames:
      maxLength: 256
      type: string
      description: Party(s) with a relationship to the account.
    DebitCardsItem:
      $ref: schemas/summary/types/debit-card-item.yaml
    ProductSummaryFlatStructureGet:
      $ref: schemas/summary/productsummary-flat-structure-get.yaml
    ProductSummaryItem:
      $ref: schemas/summary/productsummary-item.yaml
    PresentationProductItem:
      $ref: schemas/summary/product-item.yaml
    PresentationProductKindItem:
      $ref: schemas/summary/product-kind-item.yaml
    PresentationUserPreferences:
      $ref: schemas/summary/user-preferences.yaml
    StateItemQ:
      $ref: schemas/summary/state-item.yaml
    Unit:
      $ref: schemas/summary/types/time-unit.yaml
    UnsupportedMediaTypeError:
      type: object
      properties:
        message:
          type: string
          description: Any further information
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: '#/components/schemas/ErrorItem'
    ErrorItem:
      $ref: lib/schemas/error-item.yaml
    UnauthorizedError:
      $ref: lib/schemas/unauthorized-error.yaml
    BadRequestError:
      $ref: lib/schemas/bad-request-error.yaml
    NotFoundError:
      $ref: lib/schemas/not-found-error.yaml
    ForbiddenError:
      $ref: lib/schemas/forbidden-error.yaml
    InternalServerError:
      $ref: lib/schemas/internal-server-error.yaml
    NotAcceptableError:
      $ref: lib/schemas/not-acceptable-error.yaml
  examples:
    ProductSummaryFlatStructureGet:
      value:
        $ref: examples/summary/productsummary-flat-structure-get.json
    UnauthorizedError:
      value:
        $ref: lib/examples/unauthorized-error.json
    BadRequestError:
      value:
        $ref: lib/examples/bad-request-validation-error.json
    ForbiddenError:
      value:
        $ref: lib/examples/forbidden-error.json
    NotFoundError:
      value:
        $ref: lib/examples/not-found-error.json
    InternalServerError:
      value:
        $ref: lib/examples/internal-server-error.json
    NotAcceptableError:
      value:
        $ref: lib/examples/not-acceptable-error.json